repos:
  - repo: local
    hooks:
      - id: check-coverage
        name: Run Tests and Colorize Coverage
        entry: python tools/run_and_coverage.py
        language: system
        pass_filenames: false
        args: ["--threshold", "100", "--color-total-line", "--quiet-logs"]
        verbose: true

    