repos:
  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest Before Commit
        entry: pytest
        language: system
        pass_filenames: false
        args: ["--quiet-logs"]
      - id: run-coverage
        name: Run Coverage Before Commit
        entry: python tools/check_coverage.py
        language: system
        pass_filenames: false
